# Generated by Django 4.0.1 on 2022-01-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12, verbose_name='전화번호')),
                ('how_many', models.PositiveIntegerField(null=True, verbose_name='예약인수')),
                ('adults', models.PositiveIntegerField(null=True, verbose_name='성인')),
                ('kids', models.PositiveIntegerField(null=True, verbose_name='유아')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신날짜')),
                ('is_entered', models.BooleanField(verbose_name='입장여부')),
                ('is_disposed', models.BooleanField(verbose_name='처리여부')),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
    ]
