# Generated by Django 4.0.1 on 2022-01-26 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waitings', '0004_alter_waiting_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitings_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
