# Generated by Django 4.0.1 on 2022-01-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitings', '0005_alter_waiting_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiting',
            name='is_called',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='호출여부'),
        ),
    ]
