# Generated by Django 4.0.1 on 2022-01-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='매장이름')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='infos/menu/%Y/%m/%d', verbose_name='메뉴사진')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴이름')),
                ('content', models.CharField(blank=True, max_length=100, null=True, verbose_name='메뉴설명')),
                ('price', models.PositiveIntegerField(verbose_name='메뉴가격')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infocards.category')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='infos/info/%Y/%m/%d', verbose_name='소개사진')),
                ('content', models.TextField(verbose_name='소개글')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
    ]
