version: "3.7"

services:
  waiting_how:
    healthcheck:
      test: ["CMD","curl","-f", "http://172.17.0.1:8040",]
      interval: 10m
      retries: 30
      start_period: 60s
    build: .
    container_name : waiting_how
    volumes:
        - .:/usr/src/app
    ports:
        - 8040:8040
    restart: unless-stopped
    # cpus: .10
    # mem_limit: "512M"