version: "3.7"

services:
  waiting_how:
    healthcheck:
      test: ["CMD","curl","-f", "http://172.17.0.1:8040",]
      interval: 10m
      retries: 30
      start_period: 60s
    build:
      dockerfile: ./deploy/dockerfile
      context : ../
    container_name : ${CONTAINER_NAME}
    volumes:
        - /server/initial/docker_projects/nginx__1/data/site_projects/waiting/media:/usr/src/app/media
        - /server/initial/docker_projects/nginx__1/data/site_projects/waiting/static:/usr/src/app/static
    ports:
        - ${PORT}:8040
    restart: unless-stopped
    command: sh deploy/command.sh
    # cpus: .10
    # mem_limit: "512M"
    #